spring:
  application:
    name: backend-mainServer
  datasource:
    url: jdbc:mysql://energiology-db.crg0yqic8dx6.ap-northeast-2.rds.amazonaws.com:3306/dev
    username: root
    password: capstoneaplus!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

# 쿼리문 파라미터 바인딩 값 확인
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
jwt:
  secret-key: energiologyenergiologyenergiologyenergiologyenergiologyenergiologyenergiology
  access-expiration-seconds: 60
  refresh-expiration-seconds: 100

#spring:
#  application:
#    name: backend-mainServer
#  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect